# Generated by Django 4.2.3 on 2023-08-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
