# Generated by Django 4.2.1 on 2023-07-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0003_alter_new_user_date_of_born_alter_new_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='avatar',
            field=models.ImageField(default='/static/default/avatarka.jpg', upload_to='media/profile/avatar/'),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='background',
            field=models.ImageField(default='/static/default/background.jpg', upload_to='media/profile/background/'),
        ),
    ]
