# Generated by Django 4.2.3 on 2023-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0004_alter_new_user_avatar_alter_new_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='avatar',
            field=models.ImageField(default='/static/default/avatarka.jpg', upload_to='tatic/media_photo/profile/avatar/'),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='background',
            field=models.ImageField(default='/static/default/background.jpg', upload_to='tatic/media_photo/profile/background/'),
        ),
        migrations.AlterField(
            model_name='postm',
            name='images',
            field=models.ImageField(upload_to='media/post/'),
        ),
    ]
