# Generated by Django 4.2.3 on 2023-08-06 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0008_alter_new_user_avatar_alter_new_user_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends_user',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
